import type { Metadata } from "next";
import "./globals.css";
import { Provider } from "@/components/ui/provider";
import Layout from "@/components/Layout";
import { Sidebar } from "@/components/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  auth,
  children,
}: Readonly<{
  children: React.ReactNode;
  auth: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link
          href="https://shogo82148.github.io/genjyuugothic-subsets/GenJyuuGothicL-P-Medium/GenJyuuGothicL-P-Medium.css"
          type="text/css"
          rel="stylesheet"
        />

        <link
          href="https://shogo82148.github.io/genjyuugothic-subsets/GenJyuuGothicL-P-Bold/GenJyuuGothicL-P-Bold.css"
          type="text/css"
          rel="stylesheet"
        />
      </head>
      <body>
        <Provider>
          {auth}
          <Layout sidebar={<Sidebar />}>{children}</Layout>
        </Provider>
      </body>
    </html>
  );
}
